chainerrl/agents/a3c.py
chainerrl/agents/ddpg.py
chainerrl/agents/dqn.py
chainerrl/agents/nsq.py
chainerrl/agents/pgt.py
chainerrl/misc/batch_states.py

Docstrings about batch_states

---

chainerrl/policies/softmax_policy.py
chainerrl/q_functions/state_q_functions.py

to control the scale of outputs.

Add last_wscale options

---

README.md
chainerrl/agents/__init__.py
chainerrl/agents/a3c.py
chainerrl/agents/pcl.py
chainerrl/functions/__init__.py
chainerrl/functions/sum_arrays.py
chainerrl/functions/weighted_sum_arrays.py
examples/gym/train_pcl_gym.py
test_examples.sh
tests/agents_tests/test_pcl.py
tests/functions_tests/test_sum_arrays.py
tests/functions_tests/test_weighted_sum_arrays.py

Resolves #42 
Current status:
- An asynchronous non-batch version has been implemented (it works for CartPole-v0 and Pendulum-v0)
- A batch and/or gpu version has also been implemented
- prioritized replay is not implemented (waiting for #44 to be merged)

Path Consistency Learning

---

chainerrl/agents/pcl.py
chainerrl/misc/prioritized.py
chainerrl/replay_buffer.py
examples/gym/train_pcl_gym.py
tests/misc_tests/test_prioritized.py
tests/test_replay_buffer.py

in the same way as the original paper.

Use Prioritized Replay for PCL

---

chainerrl/experiments/__init__.py
chainerrl/experiments/prepare_output_dir.py
tests/experiments_tests/test_prepare_output_dir.py

- Check if it is under git control
- Increase documentation
- Use ISO 8601 by default
- Use sys.argv by default
- Add tests
- Resolves #69 
- Resolves #61

Improve prepare_output_dir function

---

chainerrl/experiments/evaluator.py
chainerrl/experiments/train_agent.py
chainerrl/experiments/train_agent_async.py
examples/ale/train_a3c_ale.py
examples/ale/train_acer_ale.py
examples/ale/train_dqn_ale.py
examples/ale/train_nsq_ale.py
examples/gym/train_a3c_gym.py
examples/gym/train_acer_gym.py
examples/gym/train_ddpg_gym.py
examples/gym/train_dqn_gym.py
examples/gym/train_pcl_gym.py

Improve scores.txt by adding columns: episodes, max and min

---

tests/agents_tests/test_a3c.py
tests/agents_tests/test_acer.py
tests/agents_tests/test_dqn_like.py
tests/agents_tests/test_nsq.py
tests/agents_tests/test_pcl.py
tests/agents_tests/test_training.py

so that training of all the agents are tested by travis ci.

Add fast agent tests that don't require success

---

chainerrl/agents/dqn.py

Resolves https://github.com/pfnet/chainerrl/issues/92

Update average_loss in update_from_episodes

---

examples/gym/train_dqn_gym.py

This is related to https://github.com/pfnet/chainerrl/issues/94

Add a docstring for train_dqn_gym.py

---

examples/gym/train_a3c_gym.py

Related to https://github.com/pfnet/chainerrl/issues/94

Add docstrings to train_a3c_gym.py

---

chainerrl/experiments/__init__.py
chainerrl/experiments/prepare_output_dir.py
tests/experiments_tests/test_prepare_output_dir.py

Support environments without git command

---

.travis.yml

Add CHAINER_VERSION config to CI

---

README.md

Fix a broken link to travis ci

Fix a broken link to travis ci

---

test_examples.sh

Specify --outdir on 2nd test

---

chainerrl/envs/ale.py

- Change grayscale formula to `0.299 R' + 0.587 G' + 0.114 B'`, where the values are gamma compressed.
- Fix `frame_skip` argument.
- Add and fix assertions.

Patches to envs.ALE

---

chainerrl/envs/abc.py

Return dict for info of env.step

---

examples/gym/train_dqn_gym.py

`--env Acrobot-v1` (DiscreteActionValue):
`--env Swimmer-v1` (QuadraticActionValue):

Draw computational graphs in train_dqn_gym.py

---

examples/ale/train_a3c_ale.py

without `--use-lstm`:
with `--use-lstm`:

Draw computational graphs in train_a3c_ale.py

---

tests/misc_tests/test_collections.py
tests/test_distribution.py

`chainer.testing` no longer exports `condition`.

Fix import chainer.testing.condition

---

chainerrl/distribution.py

Addressing issue #227:
- beta argument not used by beta variable
- min_prob variable is not passed to copy and other methods
- comments on the above 2 arguments

Tiny fix: argument passing in SoftmaxDistribution

---

requirements-dev.txt

to make easy to set up a development environment.

Add requirements-dev.txt

---

.travis.yml

https://github.com/chainer/chainer/pull/4606

[WIP] Switch autopep8 and hacking

---

.travis.yml

hacking==1.1.0 warns the current code of ChainerRL.  Remind me later.

Use hacking 1.0

---

chainerrl/agents/ppo.py

which is introduced by https://github.com/chainer/chainerrl/pull/261

Fix a too long line of PPO

---

chainerrl/agents/dqn.py

since it is obsolete and not used anywhere

Remove DQN.compute_q_values

---

examples/ale/README.md

Update README.md of examples/ale

---

chainerrl/replay_buffer.py

fixes minor typos

---

chainerrl/replay_buffer.py

Fixes a typo within a comment.

fixes typo

---

.travis.yml

This PR fixes two errors that make CI fail.

Fix Travis CI errors

---

chainerrl/agents/a3c.py
chainerrl/agents/acer.py
chainerrl/agents/pcl.py
chainerrl/agents/reinforce.py
tests/agents_tests/test_acer.py

Avoid producing warnings after the change in https://github.com/chainer/chainer/pull/4199.
I'm running the tests with https://github.com/chainer/chainer/pull/4199/commits/900b5f6b1f126330ffbd5b3c0cb0b1b558f57016

Use ()-shaped array for scalar loss

---

chainerrl/agents/ddpg.py
chainerrl/agents/double_dqn.py
chainerrl/agents/dqn.py
chainerrl/agents/ppo.py

Merge consecutive with statements

---

docs/agents.rst

Remove duplication of DQN in docs

---

examples/gym/train_ddpg_gym.py

- Humanoid-v1 is deprecated so we change to v2.

updates env in ddpg example

---

chainerrl/experiments/train_agent.py
examples/ale/train_categorical_dqn_ale.py
examples/ale/train_dqn_ale.py
examples/ale/train_nsq_ale.py
examples/ale/train_ppo_ale.py
examples/atari/dqn/train_dqn.py
examples/gym/train_categorical_dqn_gym.py
examples/gym/train_ddpg_gym.py
examples/gym/train_dqn_gym.py
examples/gym/train_pcl_gym.py
examples/gym/train_ppo_gym.py
examples/gym/train_reinforce_gym.py
examples/gym/train_trpo_gym.py
examples/quickstart/quickstart.ipynb
tests/agents_tests/basetest_training.py
tests/agents_tests/test_pcl.py
tests/agents_tests/test_ppo.py
tests/agents_tests/test_reinforce.py
tests/agents_tests/test_trpo.py

This PR changes some of the variable names and comments in train_agent_with_evaluation.

Changes variable names in train_agent_with_evaluation

---

chainerrl/agents/ppo.py

Save and load obs_normalizer of PPO

---

examples/ale/train_iqn_ale.py
examples/gym/train_iqn_gym.py
test_examples.sh

Tests of IQN examples were missing, so this PR adds them to `test_examples.sh`. Updated the examples to make them work with latest API.

Add tests of IQN examples

---

chainerrl/agents/dqn.py

Resolves https://github.com/chainer/chainerrl/issues/359

bugfix #359

---

docs/links.rst
docs/reference.rst

Some of the docstrings may not be sufficient, but I think it is better than nothing.

Add links to references

---

tests/test_distribution.py

https://travis-ci.org/chainer/chainerrl/jobs/516785404

Increase tolerance of TestGaussianDistribution.test_entropy since sometimes it failed

---

chainerrl/experiments/evaluator.py

add missing doc for the parameter `n_steps` in `eval_performance()`.

very small fix: add missing doc for eval_performance.

---

examples/atari/rainbow/train_rainbow.py

I wrote a comment that doesn't match the code.

Fixes incorrect comment.

---

.travis.yml

Use Python 3.6 for ipynb

---

examples/mujoco/reproduction/ddpg/README.md
examples/mujoco/reproduction/ppo/README.md
examples/mujoco/reproduction/td3/README.md

Algorithm times added in this PR:

Adds training times for reproduced Mujoco results

---

chainerrl/agents/double_iqn.py

Remove a tailing space of DoubleIQN

---

examples/mujoco/train_trpo_gym.py

becuase cupy started to raise an error from cupy==6.0.0.

Avoid cupy.zeros_like with numpy.ndrray

---

chainerrl/agents/a2c.py
chainerrl/agents/ddpg.py
chainerrl/agents/dqn.py
chainerrl/agents/pgt.py
examples/gym/train_pcl_gym.py
examples/gym/train_reinforce_gym.py
tests/agents_tests/test_reinforce.py
tests/test_distribution.py

This PR suppresses deprecation warnings regarding `get_device`.

Use get_device_from_id since get_device is deprecated

---

.pfnci/run.sh

~Merge #531 before this PR.~
Resolves #532

Make test_monitor.py work on flexCI

---

tests/test_distribution.py

decrease amount of decimal digits required to 4

---

.pfnci/run.sh
setup.py

I opened a new PR that is the same as #568 since TravisCI somehow tries to fetch the branch from chainer/chainerrl and fails.

Use attrs<19.2.0 with pytest

---

chainerrl/agents/categorical_double_dqn.py

Currently Categorical Double DQN performs the same update as the Categorical DQN agent.

Fixes Categorical Double DQN Error.

---

chainerrl/agents/soft_actor_critic.py

Pass env_id to replay_buffer methods to fix batch training

---

examples/atari/reproduction/rainbow/README.md

Resolves https://github.com/chainer/chainerrl/issues/559

Corrects Rainbow Results

---

CONTRIBUTING.md

Resolves https://github.com/chainer/chainerrl/issues/272

Updates contributing MD with dev-requirements install command
