chainerrl/agents/dqn.py
chainerrl/agents/nsq.py
chainerrl/explorer.py
chainerrl/explorers/__init__.py
chainerrl/explorers/additive_gaussian.py
chainerrl/explorers/additive_ou.py
chainerrl/explorers/boltzmann.py
chainerrl/explorers/epsilon_greedy.py
tests/agents_tests/test_dqn.py
tests/agents_tests/test_nsq.py
tests/explorers_tests/test_boltzmann.py

Since it requires Q-values, it is only supported by DQN (and its variants) and NSQ.

Boltzmann explorer

---

chainerrl/agents/dqn.py
chainerrl/misc/prioritized.py
chainerrl/replay_buffer.py
examples/gym/train_dqn_gym.py
tests/misc_tests/test_prioritized.py
tests/test_replay_buffer.py

Prioritized replay

---

chainerrl/experiments/evaluator.py
chainerrl/experiments/train_agent.py
chainerrl/experiments/train_agent_async.py
examples/gym/train_ddpg_gym.py
examples/gym/train_dqn_gym.py
examples/gym/train_pcl_gym.py
examples/quickstart/quickstart.ipynb

Resolves #32 
- Replace `print` sentences in `chainerrl.experiments` module with `logger.info` so that you can configure it.
- Modify the quickstart notebook to print info messages into stdout as before.
- Additionally, use `gym.undo_logger_setup` in other examples for consistency and clearness.

Use logger instead of print in experiments

---

chainerrl/experiments/prepare_output_dir.py
tests/experiments_tests/test_prepare_output_dir.py

The current directory name set by `prepare_output_dir` contains a datetime string of ISO 8061 extended format e.g. `2017-04-24T02:14:52.180466`.
It is easy to read, but its colons `:` are cumbersome, so this PR will get rid of them by switching to the ISO 8061 basic format e.g. `20170424T021452.180466`

Use ISO 8061 basic format

---

chainerrl/distribution.py
chainerrl/policies/softmax_policy.py
tests/agents_tests/test_a3c.py
tests/agents_tests/test_acer.py
tests/agents_tests/test_pcl.py
tests/test_distribution.py

- Add `min_prob` argument to `SoftmaxDistribution` and `SoftmaxPolicy`.
- Specify `min_prob` and `min_var` to stabilize agent training tests

Stabilize agent tests

---

chainerrl/experiments/__init__.py
chainerrl/experiments/hooks.py
chainerrl/experiments/train_agent.py
chainerrl/experiments/train_agent_async.py
docs/experiments.rst
examples/ale/train_a3c_ale.py
examples/ale/train_acer_ale.py
examples/ale/train_nsq_ale.py
tests/experiments_tests/test_hooks.py
tests/experiments_tests/test_train_agent.py

This PR add `StepHook` interface to customize training loops, e.g. decaying or increasing some parameters. Learning rate decaying in `chainerrl.experiments.train_agent_async` is now implemented using a hook.
Resolves #84

Use hook functions

---

chainerrl/experiments/train_agent_async.py

After this PR, If eval_interval is set to None, no evaluator nor eval_env will be created and the agent will not be evaluated.

train_agent_async without evaluation

---

docs/install.rst

because chainerrl no longer requires atari_py
Resolves #101

Remove the section for windows users

---

chainerrl/optimizers/__init__.py

so that you can write `chainerrl.optimizers.RMSpropAsync` instead of `chainerrl.optimizers.rmsprop_async.RMSpropAsync`

Add RMSpropAsync and NonbiasWeightDecay to optimizers/__init__.py

---

chainerrl/replay_buffer.py
tests/test_replay_buffer.py

Fix save/load in EpisodicReplayBuffer

---

chainerrl/agents/reinforce.py
chainerrl/experiments/train_agent.py

REINFORCE doesn't have code to initialize `self.t`. The problem has been not found because `chainer.experiemnts.train_agent` sets it, but agents should be self-contained.

Fix REINFORCE's missing initialization of t

---

chainerrl/policies/gaussian_policy.py

Deleted var_type from FCGaussianPolicyWithFixedCovariance 's docstring, 
because that's argument does not exist.
https://github.com/chainer/chainerrl/blob/master/chainerrl/policies/gaussian_policy.py#L130-L154

[policies/gaussian_policy] Improve docstring

---

chainerrl/misc/collections.py
chainerrl/replay_buffer.py
tests/misc_tests/test_collections.py

TODO:
This will happen to resolve #36 (see also #128)

Use faster queue for replay buffers

---

chainerrl/action_value.py
chainerrl/misc/chainer_compat.py
chainerrl/q_functions/state_q_functions.py

batch_matmul is going to be unavailable in Chainer v3, or would be deprecated even if https://github.com/chainer/chainer/pull/3016 is merged.

Use F.matmul instead of F.batch_matmul

---

chainerrl/agents/pcl.py
chainerrl/replay_buffer.py
examples/gym/train_dqn_gym.py
tests/test_replay_buffer.py

- Add `AbstractReplayBuffer` and `AbstractEpisodicReplayBuffer` to clarify the interfaces of replay buffers
- Change the behaviour of the `__len__` of `EpisodicReplayBuffer` and `PrioritizedEpisodicReplayBuffer` so that they now return the number of transitions, not of episodes.
- Add the `n_episodes` property to count the number of episodes
- Update the examples accordingly
- Update the tests accordingly (and fix a bug in tests)
Resolves #138

Fix episodic buffer __len__

---

chainerrl/links/mlp_bn.py
tests/links_tests/test_mlp_bn.py

- Add `nonlinearity` and `last_wscale` argument to MLPBN
- Add tests for MLPBN
The tests for MLPBN are actually not checking each configuration is applied or not, but it should be better than having no tests.

Improve MLPBN

---

chainerrl/q_functions/state_action_q_functions.py
tests/q_functions_tests/test_state_action_q_function.py

Please merge this after merging #171 
- Add `nonlinearity` and `last_wscale` aruguments to StateActionQFunctions
- Improve docstrings
- Add tests for StateActionQFunctions. They are actually not checking if each configuration is applied or not, but it should be better than having no test.

Improve StateActionQFunctions

---

tests/agents_tests/test_acer.py

Resolves #179.
After this PR, tests/agents_tests/test_acer.py will contain
- non-slow tests: `Ran 290 tests in 26.788s`, and
- slow tests: `Ran 132 tests in 772.546s`.
(All the tests in the file run without gpus.)

Mark TestBiasCorrection as slow

---

chainerrl/policies/deterministic_policy.py
tests/policies_tests/test_deterministic_policy.py

Please merge this after #171 and #172 are merged.
- Add `nonlinearity` and `last_wscale` to deterministic policies.
- Improve docstrings
- Add tests for deterministic policies

Improve deterministic policies

---

chainerrl/agents/dqn.py

The PR removes `_to_device` and `DQN._to_my_device` in `chainerrl.agents.dqn`.

Remove unused functions in DQN

---

chainerrl/experiments/prepare_output_dir.py
tests/experiments_tests/test_prepare_output_dir.py

- The first commit tests `prepare_output_dir` on condition that `git diff` is nontrivial.
- If diff of a text file contains an invalid utf-8 sequence, the output of `git diff` seems to contain an invalid sequence, too.
- The second commit fixes the bug.
The current code fails the new test: `python -m unittest tests/experiments_tests/test_prepare_output_dir.py` results
```
Ran 18 tests in 2.303s
FAILED (errors=8)
```
with e.g.
```
======================================================================
ERROR: test_prepare_output_dir (chainer.testing.parameterized.TestPrepareOutputDir_param_0)  parameter: {'argv': ['command', '--option'], 'git': True, 'time_format': '%Y%m%dT%H%M%S.%f', 'user_specified_dir': '/var/folders/zk/2tl6l77170d2b51fczxysjsw0000gn/T/tmpjqbi2uii'} …
```

Use bytestrings to write git outputs

---

chainerrl/action_value.py
tests/test_action_value.py

`QuadraticActionValue` called with `min_action=None` or `max_action=None` seems to have a bug.
Note:
```
>>> import numpy as np
>>> np.asarray(None, dtype=np.float32)
array(nan, dtype=float32)
```

Fix QuadraticActionValue and add tests

---

chainerrl/action_value.py
chainerrl/experiments/__init__.py
chainerrl/experiments/prepare_output_dir.py
chainerrl/misc/__init__.py
chainerrl/misc/draw_computational_graph.py
chainerrl/misc/is_return_code_zero.py
examples/gym/train_reinforce_gym.py
tests/experiments_tests/test_prepare_output_dir.py
tests/misc_tests/test_draw_computational_graph.py
tests/misc_tests/test_is_return_code_zero.py
tests/test_action_value.py

This PR adds `chainer.misc.draw_computational_graph` to help draw computational graphs of RL models as PNG images.
I'm not sure if I should draw a graph in every example, but it would be a good habit. For this PR I just add such code only in `examples/gym/train_reinforce_gym.py`

Add a utility function to draw a computational graph

---

examples/ale/train_dqn_ale.py

`--arch nature`:
`--arch nips`:
`--arch dueling`:

Draw computational graphs in train_dqn_ale.py

---

chainerrl/misc/random_seed.py
tests/misc_tests/test_random_seed.py

- Add `gpus` argument to `chainerrl.misc.set_random_seed` to set a seed of `cupy.random` as well as `random` and `numpy.random`.
- Add docstring and tests

Add gpus argument for chainerrl.misc.set_random_seed

---

chainerrl/agent.py
tests/test_agent.py

This PR enables nesting  AttributeSavingMixin so that agents can have child agents.

Support nesting AttributeSavingMixin

---

tests/agents_tests/test_pcl.py

Resolves #159 
It seems setting a minimum probability is harmful here.
After this PR, `test_pcl.py` succeeded 10 times in a row.
```
$ for i in `seq 10`; do nosetests -x tests/agents_tests/test_pcl.py; done
................................................................................................
----------------------------------------------------------------------
Ran 96 tests in 215.050s
OK
................................................................................................
----------------------------------------------------------------------
Ran 96 tests in 296.631s
OK
................................................................................................
----------------------------------------------------------------------
Ran 96 tests in 167.221s
OK …
```

Fix PCL tests

---

chainerrl/misc/async.py
tests/agents_tests/test_a3c.py
tests/agents_tests/test_acer.py
tests/agents_tests/test_nsq.py
tests/agents_tests/test_pcl.py

- Warn nonzero exit status. (see also #194)
- Check warnings in tests using `train_agent_async`.

Make tests check exit status of subprocesses

---

chainerrl/misc/copy_param.py
tests/misc_tests/test_copy_param.py

When we construct `QFunction`, and model parameter is not initialized (it happens when some Link is instantiated with `in_size=None`), `copy_param` will fail because the `target_link`'s `param` is `None`.
This PR is to show user-friendly error message to let the user know what is the cause of this error.
I'd like to get comment that what kind of message is better.
I'm not sure the performance degrade by checking this type error.

show error message

---

chainerrl/replay_buffer.py

If we use ReplayBuffer that loaded a buffer saved with v0.2.0, an error will occur because deque doesn't have sample() method.
This PR makes load() methods of ReplayBuffer and EpisodicReplayBuffer compatible with buffer saved with v0.2.0.

make ReplayBuffer.load() compatible with v0.2.0.

---

chainerrl/recurrent.py
docs/recurrent.rst
docs/reference.rst

Current documentation on recurrent models in ChainerRL is scarce. This PR will add a page dedicated to the recurrent model interface and utilities to the docs. The related docstrings are also improved.
This resolves #83

Add documentation about recurrent models

---

chainerrl/agent.py
tests/test_agent.py

This PR improves #134 so that `save` and `load` detect infinite loops of length >= 2.

More check on nesting AttributeSavingMixin

---

examples/ale/train_a3c_ale.py
examples/ale/train_acer_ale.py
examples/ale/train_nsq_ale.py
examples/gym/train_a3c_gym.py
examples/gym/train_acer_gym.py
examples/gym/train_pcl_gym.py

- Move `os.environ['OMP_NUM_THREADS'] = '1'` before `import chainer` to make it work
- Add it to async examples under `examples/gym`.

Fix OMP_NUM_THREADS setting

---

examples/ale/train_a3c_ale.py
examples/ale/train_dqn_ale.py

Merge #234 first.
This PR improves default random seed settings in `examples/ale/train_dqn_ale.py` and `examples/ale/train_a3c_ale.py` so that they are deterministic by default.
If this is merged, then I'll update other examples as well in another PR.

Improve random seed setting in ALE examples

---

examples/ale/train_acer_ale.py
examples/ale/train_nsq_ale.py
examples/ale/train_ppo_ale.py
examples/gym/train_a3c_gym.py
examples/gym/train_acer_gym.py
examples/gym/train_ddpg_gym.py
examples/gym/train_dqn_gym.py
examples/gym/train_pcl_gym.py
examples/gym/train_ppo_gym.py
examples/gym/train_reinforce_gym.py

in the same way as #239 
- ALE accepts `[0,2**31)`, so ALE examples use `[0,2**31)`.
- Although gym envs accepts broader range of values, numpy.random.seed accepts `[0,2**32)` as a integer, so gym examples use `[0,2**32)`.
- Logger outputs of some examples were invisible, so I changed their logger settings.

Improve random seed setting for all examples

---

chainerrl/envs/abc.py
chainerrl/envs/ale.py
chainerrl/spaces.py

gym 0.9.6 added `dtype` arg to `spaces.Box`.
The PR supports the newer interface in a backward-compatible way.
The fix in `chainerrl.envs` removes the warnings `WARN: gym.spaces.Box autodetected dtype as <` ... `>. Please provide explicit dtype.`.

Support dtype arg of spaces.Box

---

examples/ale/train_a3c_ale.py
examples/ale/train_acer_ale.py
examples/ale/train_dqn_ale.py
examples/ale/train_nsq_ale.py
examples/ale/train_ppo_ale.py
examples/gym/train_a3c_gym.py
examples/gym/train_acer_gym.py
examples/gym/train_ddpg_gym.py
examples/gym/train_dqn_gym.py
examples/gym/train_pcl_gym.py
examples/gym/train_ppo_gym.py
examples/gym/train_reinforce_gym.py

to make outdir settings consistent across the examples.
The default directory and the help string is the same as those of `examples/gym/train_trpo_gym.py`.

Set outdir to results and add help strings

---

chainerrl/experiments/train_agent.py
chainerrl/experiments/train_agent_async.py

In experiments/train_agent.py, line 84, it handles only Exception. But in experiments/train_agent_async.py, it handles only KeyboardInterrupt. I think these should handle both.

except both Exception and KeyboardInterrupt

---

chainerrl/experiments/evaluator.py
chainerrl/experiments/train_agent.py
chainerrl/experiments/train_agent_async.py
tests/experiments_tests/test_evaluator.py

- Currently, the agent is saved every time the score is improved in `train_agent_with_evaluation` and `train_agent_async`. This PR adds the `save_best_so_far_agent` option to disable it.
- Add docstrings and tests for `Evaluator` and `AsyncEvaluator`

Add an option to set whether the agent is saved every time the score is improved

---

examples/quickstart/quickstart.ipynb

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8).

Hyperlink DOI against preferred resolver

---

chainerrl/action_value.py

since it is obsolete and not used anywhere

Remove DiscreteActionValue.sample_epsilon_greedy_actions

---

chainerrl/misc/prioritized.py
chainerrl/replay_buffer.py
tests/misc_tests/test_prioritized.py
tests/test_replay_buffer.py

- pop the earliest experience when it's full
- return true probability (except for the effect of non-repetitive sampling) when the sampling is mixed with uniform sampling

FIFO prioritized replay buffer

---

examples/ale/train_dqn_ale.py

Merge #301 first.
This PR improves train_dqn_ale.py:
- use tuned DoubleDQN as better default settings (used in the Double DQN paper)
- add `--prioritized` to enable prioritized experience replay
- remove `--activation` and `--use-sdl`

Tuned DoubleDQN with prioritized experience replay

---

chainerrl/__init__.py
chainerrl/policies/gaussian_policy.py
examples/gym/train_a3c_gym.py

Resolves #276 and #281 
Since `LinearGaussianPolicyWithDiagonalCovariance` hard-codes squashing actions by tanh, replacing it with `FCGaussianPolicy` will change the behavior. I confirmed that `train_a3c_gym.py` can solve `InvertedPendulum-v1` as before by running `python train_a3c_gym.py 4 --env InvertedPendulum-v1 --arch LSTMGaussian --t-max 50`.

Remove GaussianPolicy and obsolete policies

---

chainerrl/misc/collections.py

We have previously overridden the __getitem__ operator. However, the sampling method doesn't make use of this override, and instead replicates much of the code in that method. This commit does change the semantics of what occurs in practice. However, due to the uniformity of sampling, in expectation it does the same thing. In a nutshell, both the previous code as well as this commit implement uniform sampling. However, the indexes that are chosen are different between the previous code and this one.

Make random access queue sampling code cleaner

---

chainerrl/experiments/evaluator.py
chainerrl/experiments/train_agent.py
chainerrl/experiments/train_agent_async.py
chainerrl/wrappers/__init__.py
chainerrl/wrappers/randomize_action.py
examples/ale/train_categorical_dqn_ale.py
examples/ale/train_dqn_ale.py
examples/ale/train_nsq_ale.py
tests/experiments_tests/test_evaluator.py
tests/wrappers_tests/test_randomize_action.py

We currently use `Explorer` to inject randomness to action selection in evaluation, which is common in Atari benchmarks. This use is actually irrelevant to exploration in training, so is a misnomer in my opinion.
I think we better use an env wrapper for this purpose, so that the training and evaluation code can be simpler. This is also important in #326 , where I need to implement another set of code for training and evaluation.

Use RandomizeAction wrapper instead of Explorer in evaluation

---

chainerrl/policy.py

Updated Policy class to inherit ABCMeta. 
It is because Policy class had abstract method, but did not inherit ABCMeta class.
[Python docs](https://docs.python.org/3/library/abc.html) says that decorator `@abstractmethod` requires that the class’s metaclass is ABCMeta or is derived from it.

Update Policy class to inherit ABCMeta 

---

examples/ale/atari_wrappers.py

This change saves a lot of memory. See https://github.com/openai/baselines/issues/295.

Stop caching the result of numpy.concatenate in LazyFrames

---

chainerrl/agents/dqn.py

This PR will add `n_updates` to the statistics of DQN. It is helpful for debugging.
I confirmed that
```
python examples/gym/train_dqn_gym.py --gpu -1 --replay-start-size 1000 --update-interval 1 --steps 2000
```
gets `('n_updates', 1000)`
```
INFO:chainerrl.experiments.train_agent:outdir:results/20181024T204226.214715 step:2000 episode:9 R:-1.3913073996433227
INFO:chainerrl.experiments.train_agent:statistics:[('average_q', 0.3017159130785429), ('average_loss', 0.002146864709680402), ('n_updates', 1000)]
```
, and
```
python examples/gym/train_dqn_gym.py --gpu -1 --replay-start-size 1000 --update-interval 2 --steps 2000
```
gets `('n_updates', 500)`
```
INFO:chainerrl.experiments.train_agent:outdir:results/20181024T204321.815223 step:2000 episode:9 R:-1.1019894359275235 …
```

Count updates of DQN

---

chainerrl/action_value.py
tests/test_action_value.py

This feature is used by #326 to decompose ActionValue and pass each ActionValue to explorers.

Implement __getitem__ for ActionValue

---

examples/ale/train_ppo_ale.py
examples/gym/train_ppo_gym.py

because clip_eps=0 can cause PPO to raise an error. F.clip asserts x_min < x_max.
Current PPO does not update the model at `stop_episode_and_train`, so it has not raised any errors so far. However, I think it *should* update the model at `stop_episode_and_train` when the amount of transitions reaches `update_interval` by that call of `stop_episode_and_train`.
#326 will change the behavior of PPO so that it will update the model in such cases, thus depends on this PR.

Make clip_eps positive

---

chainerrl/wrappers/__init__.py
chainerrl/wrappers/render.py
examples/ale/train_a2c_ale.py
examples/ale/train_a3c_ale.py
examples/ale/train_acer_ale.py
examples/ale/train_categorical_dqn_ale.py
examples/ale/train_dqn_ale.py
examples/ale/train_dqn_batch_ale.py
examples/ale/train_nsq_ale.py
examples/ale/train_ppo_ale.py
examples/atari/dqn/train_dqn.py
examples/gym/train_a2c_gym.py
examples/gym/train_a3c_gym.py
examples/gym/train_acer_gym.py
examples/gym/train_categorical_dqn_gym.py
examples/gym/train_ddpg_gym.py
examples/gym/train_dqn_gym.py
examples/gym/train_pcl_gym.py
examples/gym/train_ppo_batch_gym.py
examples/gym/train_ppo_gym.py
examples/gym/train_reinforce_gym.py
examples/gym/train_trpo_gym.py
tests/wrappers_tests/test_render.py

This PR adds `chainerrl.wrappers.Render`, an Env wrapper that calls `env.render` after every `env.reset` and `env.step`. All the examples that uses `chainerrl.misc.env_modifiers.make_rendered` switch to use the new wrapper.
Somehow `chainerrl.misc.env_modifiers.make_rendered` stopped to work correctly for atari environments, and this PR is needed to fix this issue.
I confirmed that all the affected examples work with rendering enabled.

Render wrapper

---

chainerrl/experiments/train_agent_async.py
tests/experiments_tests/test_train_agent_async.py

- Resolves #342 
- Corrects the termination condition of `train_agent_async`.
- Adds tests for `train_agent_async`
I confirmed that all the tests pass.

Close envs in async training

---

MANIFEST.in
README.md
setup.py

Reference: #355 
Changed the following files:
- `setup.py`: use `README.md` as basis for PyPI project description
- `MANIFEST.in`: includes `LICENSE` and `README.md`
- `README.md`: use raw github content for assets (logo, gifs) instead of relative paths

Add long description for pypi 

---

tests/experiments_tests/test_train_agent_async.py

- https://travis-ci.org/chainer/chainerrl/jobs/463226829
```
for i, call in enumerate(hook.call_args_list):
args, kwargs = call
self.assertTrue(any(args[0] == env for env in envs))
self.assertEqual(args[1], agent)
>           self.assertEqual(args[2], i + 1)
E           AssertionError: 5 != 4
```
- https://travis-ci.org/chainer/chainerrl/jobs/463226831
```
if self.num_envs == 1:
self.assertEqual(hook.call_count, steps)
elif self.num_envs > 1:
>           self.assertGreater(hook.call_count, steps)
E           AssertionError: 3 not greater than 5
```

Fix `TestTrainAgentAsync`

---

setup.py

`pip install -e .` raises `UnicodeDecodeError` when `LC_CTYPE` is `POSIX`.
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/user/setup.py", line 31, in <module>
long_description=open('README.md').read(),
File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2004: ordinal not in range(128)
```
To reproduce this error, `LC_ALL=POSIX pip install -e .`.
This PR fixes this error by specifying the encoding when reading README.md.

Avoid UnicodeDecodeError in setup.py

---

chainerrl/experiments/evaluator.py
chainerrl/experiments/train_agent.py
chainerrl/experiments/train_agent_async.py
chainerrl/experiments/train_agent_batch.py
chainerrl/wrappers/__init__.py
chainerrl/wrappers/atari_wrappers.py
chainerrl/wrappers/continuing_time_limit.py
examples/ale/train_a2c_ale.py
examples/ale/train_a3c_ale.py
examples/ale/train_acer_ale.py
examples/ale/train_categorical_dqn_ale.py
examples/ale/train_dqn_ale.py
examples/ale/train_dqn_batch_ale.py
examples/ale/train_nsq_ale.py
examples/ale/train_ppo_ale.py
examples/atari/dqn/train_dqn.py
tests/experiments_tests/test_evaluator.py
tests/experiments_tests/test_train_agent.py
tests/experiments_tests/test_train_agent_async.py
tests/experiments_tests/test_train_agent_batch.py
tests/wrappers_tests/test_continuing_time_limit.py

This PR enables an env to send a signal that indicates it needs a reset via the `info` dict returned by `env.step` without setting `done=True`.
This functionality is needed to implement to strictly follow the training protocol of DeepMind on Atari games, which limits the number of frames of an episode ignoring life losses, while the agent still sees episodes that terminate by a life loss.

Allow envs to send a 'needs_reset' signal

---

chainerrl/misc/batch_states.py
tests/misc_tests/test_batch_states.py

This change enables the default batch_states function to handle tuple-shaped observations.
I'm running the whole tests.

Use chainer.dataset.concat_examples in batch_states

---

docs/install.rst

A small change in the installation documentation. This PR simply expands the instructions on how to install ChainerRL from the source code.

A small change to the installation documentation

---

chainerrl/misc/async_.py
tests/agents_tests/test_nsq.py
tests/misc_tests/test_async.py

When subprocesses exit with nonzero exitcode, `run_async` raise warnings. Some tests check the number of warnings, but they do not work when there is another code that raises warnings, leading to failure in CI of current master.
This PR specifies a warning category for nonzero exitcode, `AbnormalExitCodeWarning`, and the tests will check warnings of that category.

Use AbnormalExitCodeWarning for nonzero exitcode warnings

---

.travis.yml
CONTRIBUTING.md
requirements-dev.txt
tests/links_tests/test_noisy_linear.py

Currently, `pipenv install -r requirements-dev.txt` fails due to version inconsistency of `pycodestyle` caused by `hacking`:
- autopep8==1.4.3 requires pycodestyle>=2.4.0
- hacking==1.1.0 requires flake8<2.7.0,>=2.6.0
- flake8==2.6.2 requires pycodestyle<2.1,>=2.0
This PR drops `hacking` so we use `flake8` instead.
Chainer already dropped `hacking` https://github.com/chainer/chainer/pull/4864

Drop hacking

---

chainerrl/agents/dqn.py
chainerrl/replay_buffer.py

- it is no longer thread-safe
- its format was not consistent with other docstrings
- information is added

Fix DQN.update's docstring

---

chainerrl/optimizers/nonbias_weight_decay.py
tests/optimizer_tests/test_nonbias_weight_decay.py

`NonbiasWeightDecay` does not work due to API changes of Chainer. This PR fixes this issue and adds tests for it.
Resolves #388

Make NonbiasWeightDecay work again

---

README.md

Adds IQN to the readme, since it's now implemented.

adds implicit quantile networks to readme

---

chainerrl/agents/ddpg.py

#317 broke DDPG's episodic training and made `tests/agents_tests/test_ddpg.py` fail. This PR fixes it.

Fix episodic training of DDPG

---

chainerrl/agents/pgt.py

#317 broke PGT's training and made `tests/agents_tests/test_pgt.py` fail. This PR fixes it.

Fix PGT's training

---

chainerrl/agents/residual_dqn.py

#317 broke ResidualDQN's training and made `tests/agents_tests/test_residual_dqn.py` fail. This PR fixes it.

Fix ResidualDQN's training

---

tests/agents_tests/test_a3c.py

It seems that current A3C tests sometimes fail. When I run
```
for i in `seq 10`; do pytest -v tests/agents_tests/test_a3c.py; done
```
, only 4 out of 10 suceeded. I believe that it was more stable in the past, but I'm not sure what made it unstable.
This PR tunes its hyperparameters to stabilize and speed up the A3C tests.
Before this commit:
- test_a3c.py succeeds only 4 times out of 10
- when suceeding, it takes 90-120 seconds
After this commit:
- it suceeds 10/10
- it takes 23-28 seconds

Stabilize and speed up A3C tests

---

tests/agents_tests/test_acer.py

- `use_lstm=False` was tested for `t_max=1,2,5`. This PR changes it to `t_max=1,2` because I think it is sufficient. `use_lstm=True=True` is tested for `t_max=5` as before.
- Test cases where `n_times_replay=0` and `disable_online_update=True` were tested twice. This PR skips one of them.
- Maximum of timesteps is reduced to avoid consuming too much time on failed tests.

Reduce ACER's test cases and maximum timesteps

---

.travis.yml

This PR fixes the error of `from typing import Type` in Travis CI caused by `tornado==6.0.1` by switching from Python 3.5 to 3.6.
https://travis-ci.org/chainer/chainerrl/jobs/504242079

Use Python 3.6 in Travis CI

---

examples/atari/iqn/README.md

I had accidentally put the score that IQN achieves for Defender under Demon Attack. I have fixed it here. 
The reported score can be found in the final page of: https://arxiv.org/pdf/1806.06923.pdf

Fixes scores for Demon Attack

---

examples/atari/dqn/README.md

This PR includes the following:
- Benchmarking of the scores attained by the DQN example
- A comparison of the scores against the reported DQN results
- Information on the average training time of the DQN
- Information on the evaluation protocol used.

Benchmarks DQN example

---

examples/grasping/train_dqn_batch_grasping.py

`gym==0.12.1` started to check types of observations in `gym.spaces.Tuple`, but the observation space of the env used in the grasping example is not correctly set, causing CI failures.
This PR set observation_space correctly to fix the issue.

Set observation_space of kuka env correctly

---

examples/ale/train_dqn_ale.py

Ran the following two commands on the new program:
- `python3 examples/ale/train_dqn_ale.py --gpu -1 --eval-interval 50 --steps 175 --replay-start-size 30 --eval-n-runs 1`
- `python3 examples/ale/train_dqn_ale.py --gpu -1 --eval-interval 50 --steps 175 --replay-start-size 35 --eval-n-runs 1 --noisy-net-sigma 0.2`
Both programs ran to completion.

Fixes error in setting explorer in DQN ALE example.

---

examples/ale/train_a3c_ale.py

In the comment in the code, `processes` shouldn't be plural.

Fixes minor grammar mistake in A3C ALE example

---

chainerrl/agents/a2c.py
chainerrl/agents/dqn.py
chainerrl/agents/iqn.py
chainerrl/agents/ppo.py

This PR resolves #335 (again).

Replace Variable.data with Variable.array (again)

---

chainerrl/agents/iqn.py

`batch_next_state` may not be an ndarray, e.g., when observations are tuples of ndarrays. To avoid an error caused by this, use `exp_batch['reward']` to get the batch size since it is always an ndarray

Make IQN work with tuple observations

---

chainerrl/experiments/evaluator.py
tests/experiments_tests/test_evaluator.py

Agents are expected to see when episodes end so that they can reset their internal recurrent states. However, ChainerRL currently fails to make sure that agent can see it in following two cases:
- Time-based evaluation: when sufficient amount of steps are consumed, evaluation episodes are stopped without notifying the agent.
- Batch evaluation: when sufficient amount of episodes are finished, other envs' unfinished episodes are stopped without notyfing the agent.
This is a bug. This PR fixes it.

Make sure the agent sees when episodes end

---

README.md

Although pfnet/chainer still works, chainer/chainer is correct now.

Link to chainer/chainer, not pfnet/chainer

---

chainerrl/q_functions/state_q_functions.py

Add missing docstring & small fix for `q_functions.state_q_functions.FCStateQFunctionWithDiscreteAction`.

fix & add docstring for FCStateQFunctionWithDiscreteAction

---

chainerrl/env.py
chainerrl/wrappers/__init__.py
chainerrl/wrappers/vector_frame_stack.py
examples/ale/train_dqn_batch_ale.py
tests/wrappers_tests/test_vector_frame_stack.py

This PR adds
- `VectorEnvWrapper`: an VectorEnv analog to `gym.Wrapper`
- `VectorStackFrame`: an VectorEnv analog to `chainerrl.wrappers.atari_wrappers.StackFrame`
to reduce memory usage in `train_dqn_batch_ale.py`.
The current example wraps envs by `StackFrame` then by `MultiprocessVectorEnv`. This is actually memory inefficient because when `LazyFrames` is passed between processes via Pipe, it becomes not lazy anymore due to pickling. This PR solves the issue by stacking frames in the main process.
TODO:

Add VectorStackFrame to reduce memory usage in train_dqn_batch_ale.py

---

chainerrl/wrappers/atari_wrappers.py
tests/wrappers_tests/test_atari_wrappers.py

This PR makes `chainerrl.wrappers.atari_wrappers.FrameStack` follow `low`, `high` and `dtype` of  wrapping env's observation space.
Also some tests for `chainerrl.wrappers.atari_wrappers.FrameStack` are added, but tests for other classes defined in `chainerrl.wrappers.atari_wrappers` are still missing.
See also: #443

make FrameStack follow original spaces

---

examples/ale/train_a2c_ale.py
examples/ale/train_dqn_batch_ale.py
examples/gym/train_a2c_gym.py
examples/gym/train_ddpg_batch_gym.py
examples/gym/train_ppo_batch_gym.py
tests/wrappers_tests/test_vector_frame_stack.py

I noticed some of batch training examples have a bug that unintentionally uses same process indices (thus same random seeds!) across env processes. This PR fixes the bug.
You can see the current and new behaviors by running the code below. 
```
import functools
import chainerrl
import gym
num_envs = 4
def make_env(process_idx, test):
print(process_idx, test)
return gym.make('Pendulum-v0')
def make_batch_env_old(test):
return chainerrl.envs.MultiprocessVectorEnv(
[(lambda: make_env(idx, test))
for idx, env in enumerate(range(num_envs))])
def make_batch_env_new(test):
return chainerrl.envs.MultiprocessVectorEnv(
[functools.partial(make_env, idx, test)
for idx, env in enumerate(range(num_envs))])
print('make_batch_env_old')
make_batch_env_old(test=False)
make_batch_env_old(test=True) …
```

Fix a bug of unintentionally using same process indices

---

chainerrl/wrappers/atari_wrappers.py

Currently, cv2 dependency is intended to be optional and not specified in `setup.py`. However, because `cv2` is imported in `atari_wrappers.py`, which is imported when users import `chainerrl`, so users cannot use chainerrl without cv2.
This PR makes cv2 truly optional.

Make cv2 dependency optional

---

examples/atari/rainbow/README.md

- Adds results for Carnival
- Removes bolding of scores for domains when either the rainbow paper or ChainerRL doesn't have reported results.
The new README looks like this: https://github.com/prabhatnagarajan/chainerrl/tree/rainbow_scores/examples/atari/rainbow

Improves Rainbow README

---

chainerrl/agents/ddpg.py
chainerrl/agents/dqn.py
chainerrl/replay_buffer.py
examples/ale/train_dqn_batch_ale.py
tests/test_replay_buffer.py

~Merge #443 before this PR.~
Current replay buffers with num_steps > 1 or episodic are not correct in batch training because they cannot know which env a given transition came from.
This PR adds the `env_id` argument to two methods of replay buffers: `append` and `stop_current_episode`. From `env_id` replay buffers can know which env a given transition came from and which env's episode is stopped.
TODO:

Pass env_id to replay buffer methods to correctly support batch training

---

chainerrl/wrappers/atari_wrappers.py
tests/wrappers_tests/test_atari_wrappers.py

`ScaledFloatFrame.observation_space` was not properly converted and it resulted in some inconsistency, such as `observation_space.low/high/sample/contains`.

fix ScaledFloatFrame.observation_space

---

requirements.txt
setup.py

The latest version of `gym` dropped support of underscore methods in env_wrappers like `_observation`.
ChainerRL now implements underscore methods, we need to fix the version of `gym`.
Here is my installation log (at a brand new virtualenv):
```
$ python setup.py install
*snip*
$ pip freeze
cached-property==1.5.1
certifi==2019.3.9
chainer==7.0.0a1
chainerrl==0.6.0
chardet==3.0.4
filelock==3.0.12
future==0.17.1
gym==0.12.1
idna==2.8
numpy==1.16.4
Pillow==6.0.0
protobuf==3.7.1
pyglet==1.4.0b1
requests==2.22.0
scipy==1.3.0
six==1.12.0
typing==3.6.6
typing-extensions==3.7.2
urllib3==1.25.3
```

update requirements.txt and setup.py for gym

---

examples/ale/train_dqn_ale.py
examples/ale/train_dqn_batch_ale.py
examples/atari/rainbow/train_rainbow.py
examples/gym/train_dqn_gym.py

The specified value for `noisy_net_sigma` was ignored when NoisyNet is enabled.

Apply `noisy_net_sigma` parameter

---

examples/README.md

We have descriptions of all the subfolders in the examples directory, except for the `mujoco` folder. This PR addresses that.

Adds reference to mujoco folder in the examples README

---

chainerrl/envs/multiprocess_vector_env.py

Add warning about numpy 1.16.0

---

chainerrl/wrappers/atari_wrappers.py
chainerrl/wrappers/cast_observation.py
chainerrl/wrappers/randomize_action.py
chainerrl/wrappers/scale_reward.py
examples/grasping/README.md
examples/grasping/train_dqn_batch_grasping.py
requirements.txt
setup.py

- Stop using underscore methods in all the wrappers
- Require `pybullet>=2.4.9` for the grasping example because older ones do not work with `gym>=0.12.2`
- Revert the change requiring `gym<=0.12.1` by https://github.com/chainer/chainerrl/pull/461

Support `gym>=0.12.2` by stopping to use underscore methods in gym wrappers

---

chainerrl/replay_buffer.py
tests/test_replay_buffer.py

Match EpisodicReplayBuffer.sample with ReplayBuffer.sample

---

chainerrl/links/noisy_chain.py
tests/links_tests/test_noisy_chain.py

The PR fixes #488 and adds support for `chainer.Sequential`.

Make `to_factorized_noisy` work with sequential links

---

.pfnci/config.pbtxt
.pfnci/hint.pbtxt
.pfnci/run.sh
.pfnci/script.sh

Currently, some imosCI test targets are running, but I'd like to stop them and add the following targets instead:
- https://ci.preferred.jp/chainerrl.py3.gpu/
- https://ci.preferred.jp/chainerrl.py3.cpu/
- https://ci.preferred.jp/chainerrl.py3.chainer4/
The details for each test target should be written in .pfnci/config.pbtxt.

Add CI configs

---

chainerrl/agents/ppo.py
chainerrl/links/stateless_recurrent.py
chainerrl/misc/conjugate_gradient.py
chainerrl/policies/gaussian_policy.py
chainerrl/q_functions/state_q_functions.py
tests/misc_tests/test_prioritized.py
tests/test_ale.py
tests/test_replay_buffer.py

https://github.com/PyCQA/flake8-bugbear#list-of-warnings
> B007: Loop control variable not used within the loop body. If this is intended, start the name with an underscore.

Fix B007: Loop control variable not used within the loop body

---

chainerrl/experiments/train_agent.py
chainerrl/experiments/train_agent_async.py
chainerrl/experiments/train_agent_batch.py

https://github.com/PyCQA/flake8-bugbear#list-of-warnings
> B006: Do not use mutable data structures for argument defaults. All calls reuse one instance of that data structure, persisting changes between them.

Fix B006: Do not use mutable data structures for argument defaults.

---

chainerrl/agents/acer.py

It is simpler than `backward` with `backprop_truncated`.
Todo

Use chainer.grad in ACER

---

.travis.yml

Resolves #519.
- Specify ubuntu 16.04 (xenial) as a distribution to use in Travis CI. See #519 for the reason.
- Use xvfb service since the previous way does not work with 16.04.
- Install `fleeglut3-dev` to avoid `ImportError: Library "GLU" not found.`

Specify ubuntu 16.04 for Travis CI and modify a dependency accordingly

---

chainerrl/replay_buffer.py

Resolves #527 
Please run gpu slow tests `tests/agents_tests/test_dqn.py` to see if the issue is solved.

Fix a bug in `batch_recurrent_experiences` regarding next_action

---

tests/links_tests/test_stateless_recurrent_sequential.py

Resolves #530 
Reviewer: please test with chainer==7.0.0b3.

Fix import error when chainer==7.0.0b3

---

chainerrl/agents/categorical_dqn.py

as the latter is deprecated by cupy from v4.
This PR suppresses deprecation warnings from cupy:
> DeprecationWarning: cupy.scatter_add is deprecated. Use cupyx.scatter_add instead.
`cupy.scatter_add` is available from cupy v4, which is the minimum version we support.

Use cupyx.scatter_add instead of cupy.scatter_add

---

tests/test_distribution.py

Before this PR, both mean and var is sampled uniformly from [0,1]. This is not good because
- the case when mean has negative elements is not tested, and
- variance close to zero can lead to numerical instability, leading to failure in tests. (https://ci.preferred.jp/chainerrl.py3.cpu/26601/)
This PR changes the parameter distributions so that mean is sampled from N(0,1) while variance is sampled from U(0.5,2).
I locally ran TestGaussian 100 times without failure.

Improve parameter distributions used in TestGaussianDistribution

---

README.md

We currently don't specify in the README whether an agent is a batch agent or not. This PR does this.
Source for the data:
DQN, DDPG, PPO, TRPO, TD3, PCL, and SAC are batch agents by definition.
Categorical DQN, Rainbow (CategoricalDoubleDQN), and IQN are BatchAgents by inheriting DQN.
A3C is a BatchAgent via A2C. 
NSQ is a BatchAgent via normal DQN with an N-Step buffer. Not sure how factually correct we're trying to be in calling these two agents "Batch" agents.
ACER is simply not a batch agent.

Adds List of Batch Agents to the README

---

chainerrl/agents/sarsa.py

~Merge #528 first.~
Resolves #535 
Please run gpu slow tests tests/agents_tests/test_sarsa.py to see if the issue is solved.

Fix ValueError in SARSA with GPU

---

.pfnci/config.pbtxt

Default is 10min. I skipped `chainerrl.py2.cpu` because it is not used.

Increase flexCI's time limit to 20min

---

chainerrl/replay_buffers/prioritized.py
examples/atari/reproduction/rainbow/train_rainbow.py
tests/test_replay_buffer.py

This PR fixes the wrong computation of `min_probability` in `PrioritizedReplayBuffer` when `normalize_by_max == 'batch'`, which is the default behavior. The previous behavior was unexpectedly the same as `normalize_by_max == 'memory'`.

Fix weight normalization inside prioritized experience replay

---

examples/atari/reproduction/a3c/README.md

Removes GPU option from README

---

examples/atari/reproduction/a3c/README.md

Previously, the A3C results reported the best intermediate score every 1M timesteps. Now it reports  the best intermediate score every 250K timesteps.

Adds proper A3C scores

---

.pfnci/hint.pbtxt

Several DDPG tests seem to be failing due to timeouts on the ddpg tests. This PR adds time to the DDPG.
E.g. : https://ci.preferred.jp/chainerrl.py3.gpu.slow/49475/
https://ci.preferred.jp/chainerrl.py3.cpu.slow/49125/

Adds time to DDPG Tests

---

examples/atari/reproduction/a3c/train_a3c.py

Since the best network is the reported score for A3C, we want to store the best network for the model release.

Basic Script Fix

---

chainerrl/misc/pretrained_models.py

Resolves https://github.com/chainer/chainerrl/issues/551
I haven't tested with windows, but this fix should work. The issue with windows was that os.path.join uses windows file paths, so downloading from the web uses windows file paths breaks. This explicitly uses posix paths instead.
I've tested an example model download with this updated code and it works. Also note that the model download is tested in the CI.

Uses posix to avoid path issues for windows users
